language: php

php: [5.5, 5.6, hhvm]

before_script:
  - export COMPOSER_ROOT_VERSION=2.0.0-RC3
  - composer selfupdate
  - composer install --prefer-source
  - ./install.sh

script:
  - ./vendor/bin/phpspec --no-interaction -vvv --format=pretty run
  - ./vendor/bin/behat --format=pretty
